/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:c9ce93ad-4d65-4185-aad8-c92fec05dbde",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IBvQt8HrS",
    "aws_user_pools_web_client_id": "f0qk6t6a8umi82p9122r7ffd4",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "bookstoreimages120932-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://62yds54bnfbuhol4fgjo5kqhbm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-bo7d55jjjbbblmicmdaoxbdqia",
    "aws_content_delivery_bucket": "mybookstore-20220702224554-hostingbucket-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://mybookstore-20220702224554-hostingbucket-prod.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
